# -*- coding: utf-8 -*-
"""QUESTION2 labtest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ShL3X_RSOd0gBm9oCRWpy38QFOydlhTa
"""

import streamlit as st
import json

st.title("🏠 Smart AC Controller")
st.write("This app decides AC settings based on home conditions using a rule-based system.")

# --- Home condition inputs ---
temperature = st.number_input("Temperature (°C)", value=22)
humidity = st.number_input("Humidity (%)", value=46)
occupancy = st.selectbox("Occupancy", ["OCCUPIED", "EMPTY"])
time_of_day = st.selectbox("Time of Day", ["MORNING", "AFTERNOON", "EVENING", "NIGHT"])
windows_open = st.checkbox("Windows Open", value=False)

home_facts = {
    "temperature": temperature,
    "humidity": humidity,
    "occupancy": occupancy,
    "time_of_day": time_of_day,
    "windows_open": windows_open
}

# --- Rules JSON ---
rules_json = '''
[
  {
    "name": "Windows open → turn AC off",
    "priority": 100,
    "conditions": [["windows_open","==",true]],
    "action": {"ac_mode":"OFF","fan_speed":"LOW","setpoint":null,"reason":"Windows are open"}
  },
  {
    "name": "No one home → eco mode",
    "priority": 90,
    "conditions": [["occupancy","==","EMPTY"],["temperature",">=",24]],
    "action": {"ac_mode":"ECO","fan_speed":"LOW","setpoint":27,"reason":"Home empty; save energy"}
  },
  {
    "name": "Hot & humid (occupied) → cool strong",
    "priority": 80,
    "conditions": [["occupancy","==","OCCUPIED"],["temperature",">=",30],["humidity",">=",70]],
    "action": {"ac_mode":"COOL","fan_speed":"HIGH","setpoint":23,"reason":"Hot and humid"}
  },
  {
    "name": "Hot (occupied) → cool",
    "priority": 70,
    "conditions": [["occupancy","==","OCCUPIED"],["temperature",">=",28]],
    "action": {"ac_mode":"COOL","fan_speed":"MEDIUM","setpoint":24,"reason":"Temperature high"}
  },
  {
    "name": "Slightly warm (occupied) → gentle cool",
    "priority": 60,
    "conditions": [["occupancy","==","OCCUPIED"],["temperature",">=",26],["temperature","<",28]],
    "action": {"ac_mode":"COOL","fan_speed":"LOW","setpoint":25,"reason":"Slightly warm"}
  },
  {
    "name": "Night (occupied) → sleep mode",
    "priority": 75,
    "conditions": [["occupancy","==","OCCUPIED"],["time_of_day","==","NIGHT"],["temperature",">=",26]],
    "action": {"ac_mode":"SLEEP","fan_speed":"LOW","setpoint":26,"reason":"Night comfort"}
  },
  {
    "name": "Too cold → turn off",
    "priority": 85,
    "conditions": [["temperature","<=",22]],
    "action": {"ac_mode":"OFF","fan_speed":"LOW","setpoint":null,"reason":"Already cold"}
  }
]
'''

rules = json.loads(rules_json)

# --- Rule evaluation function ---
def evaluate_rules(rules, facts):
    matched_rules = []
    for rule in rules:
        conditions_met = True
        for cond in rule["conditions"]:
            key, op, value = cond
            fact_value = facts.get(key)

            if op == "==":
                if fact_value != value:
                    conditions_met = False
                    break
            elif op == ">=":
                if fact_value < value:
                    conditions_met = False
                    break
            elif op == "<=":
                if fact_value > value:
                    conditions_met = False
                    break
            elif op == "<":
                if fact_value >= value:
                    conditions_met = False
                    break
            elif op == ">":
                if fact_value <= value:
                    conditions_met = False
                    break

        if conditions_met:
            matched_rules.append((rule["priority"], rule["name"], rule["action"]))

    matched_rules.sort(reverse=True)
    return matched_rules[0] if matched_rules else None

# --- Run evaluation ---
if st.button("Evaluate AC Settings"):
    result = evaluate_rules(rules, home_facts)
    if result:
        priority, rule_name, action = result
        st.success(f"Rule triggered: {rule_name} (Priority {priority})")
        st.write(f"**AC Mode:** {action['ac_mode']}")
        st.write(f"**Fan Speed:** {action['fan_speed']}")
        st.write(f"**Reason:** {action['reason']}")
    else:
        st.warning("No rule matched.")