# -*- coding: utf-8 -*-
"""QUESTION2 labtest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ShL3X_RSOd0gBm9oCRWpy38QFOydlhTa
"""

# Home condition input
home_facts = {
    "temperature": 22,
    "humidity": 46,
    "occupancy": "OCCUPIED",
    "time_of_day": "NIGHT",
    "windows_open": False
}
import json

# Paste the JSON content here
rules_json = '''
[
    {
        "name": "Night Time Cooling",
        "priority": 10,
        "conditions": [
            ["time_of_day", "==", "NIGHT"],
            ["temperature", ">=", 25],
            ["windows_open", "==", false]
        ],
        "action": {
            "ac_mode": "COOL",
            "fan_speed": "MEDIUM",
            "reason": "It's warm at night, cooling down."
        }
    },
    {
        "name": "Day Time Heating",
        "priority": 8,
        "conditions": [
            ["time_of_day", "==", "DAY"],
            ["temperature", "<", 18]
        ],
        "action": {
            "ac_mode": "HEAT",
            "fan_speed": "LOW",
            "reason": "It's cold during the day, warming up."
        }
    },
    {
        "name": "High Humidity Alert",
        "priority": 7,
        "conditions": [
            ["humidity", ">=", 60],
            ["occupancy", "==", "OCCUPIED"]
        ],
        "action": {
            "ac_mode": "DRY",
            "fan_speed": "HIGH",
            "reason": "High humidity detected, drying air."
        }
    },
    {
        "name": "Ventilate with Open Windows",
        "priority": 5,
        "conditions": [
            ["windows_open", "==", true],
            ["temperature", ">=", 20],
            ["temperature", "<=", 24]
        ],
        "action": {
            "ac_mode": "FAN",
            "fan_speed": "LOW",
            "reason": "Windows open, circulating air."
        }
    },
    {
        "name": "Default AC Off",
        "priority": 1,
        "conditions": [],
        "action": {
            "ac_mode": "OFF",
            "fan_speed": "OFF",
            "reason": "No specific rule matched, AC off."
        }
    }
]
'''

rules = json.loads(rules_json)

def evaluate_rules(rules, facts):
    matched_rules = []

    for rule in rules:
        conditions_met = True
        for cond in rule["conditions"]:
            key, op, value = cond
            if op == "==":
                if facts.get(key) != value:
                    conditions_met = False
                    break
            elif op == ">=":
                if facts.get(key) < value:
                    conditions_met = False
                    break
            elif op == "<":
                if facts.get(key) >= value:
                    conditions_met = False
                    break
            elif op == "<=":
                if facts.get(key) > value:
                    conditions_met = False
                    break
        if conditions_met:
            matched_rules.append((rule["priority"], rule["name"], rule["action"]))

    # Sort by priority descending
    matched_rules.sort(reverse=True)
    return matched_rules[0] if matched_rules else None

result = evaluate_rules(rules, home_facts)

if result:
    priority, rule_name, action = result
    print(f"Rule triggered: {rule_name} (Priority {priority})")
    print(f"AC Mode: {action['ac_mode']}")
    print(f"Fan Speed: {action['fan_speed']}")
    print(f"Reason: {action['reason']}")
else:
    print("No rule matched.")